export type CNPJSintegra = {
    cnpj: string,
    tipo: string,
    situacao: string,
    abertura: string,
    nome: string,
    fantasia: string,
    atividade_principal: [],
    atividade_principal_code: string,
    atividade_principal_text: string,
    natureza_juridica: string,
    logradouro: string,
    numero: string,
    complemento: string,
    bairro: string,
    cep: string,
    municipio: string,
    uf: string,
    email: string,
    telefone: string,
}